### ISSUE TITLE
Could not find ..settings.reference.json

### ISSUE THREAD

**Issue by mik3up** [PetterKraabol/Twitch-Chat-Downloader#67]
Hi, I am getting the following error "[Critical]: Could not find /Users/user/anaconda3/lib/python3.7/site-packages/tcd/settings.reference.json" when running any tcd command.

I just installed via pip the tcd package but I could not find any documentation around this missing file.

I would like to use this tool for a project as my main dataset, any help would be really appreciated! 

thank you!

**Comment by PetterKraabol** [comment]
Hi, there's unfortunately an issue when running tcd in a virtual environment such as Conda or pipenv.
I'd recommend installing tcd from a regular Python install for now.

Similar to #65

**Comment by PetterKraabol** [comment]
Turns out the `manifest.in` file is case-sensitive for some programs and should be `MANIFEST.in` instead. Pipenv had the same problem, which is now fixed, so I assume the same goes for Conda.

Try installing tcd now (version 3.0.7)

**Comment by mik3up** [comment]
Thanks for being so quick on this! I am hoping on starting parsing data
tomorrow evening for my project.

I did a pip install --upgrade --user tcd

Now I am seeing the following error when I type 'tcd' in bash.

[11:45:47][Twitch_Project] tcd

Traceback (most recent call last):

  File "/Users/test/anaconda3/bin/tcd", line 7, in <module>

    from tcd import main

  File "/Users/test/.local/lib/python3.7/site-packages/tcd/__init__.py",
line 7, in <module>

    from .downloader import Downloader

  File "/Users/test/.local/lib/python3.7/site-packages/tcd/downloader.py",
line 12, in <module>

    from .formatter import Formatter

  File "/Users/test/.local/lib/python3.7/site-packages/tcd/formatter.py",
line 5, in <module>

    from .formats.custom import Custom

  File
"/Users/test/.local/lib/python3.7/site-packages/tcd/formats/custom.py",
line 5, in <module>

    from tcd.formats.format import Format

  File
"/Users/test/.local/lib/python3.7/site-packages/tcd/formats/format.py",
line 6, in <module>

    class Format:

  File
"/Users/test/.local/lib/python3.7/site-packages/tcd/formats/format.py",
line 8, in Format

    def __init__(self, video: twitch.helix.Video, format_name: str):

AttributeError: module 'twitch.helix' has no attribute 'Video'



Do you have any suggestions?


Thank you,

-

Michael

**Comment by PetterKraabol** [comment]
I've made some changes to imports d28abb489b12f47729fc2f86420d49f7c2413aee. Try version 3.0.8.

**Comment by mik3up** [comment]
Hi Petter,

Just tried again and am still having a similar error below... do you have
any ideas?

This happens on both tcd and twitch client where it says twitch obj does
not have .helix attribute.

Thank you!

[14:56:00][Twitch_Project] tcd

Traceback (most recent call last):

  File "/Users/local/anaconda3/bin/tcd", line 7, in <module>

    from tcd import main

  File
"/Users/local/anaconda3/lib/python3.7/site-packages/tcd/__init__.py", line
7, in <module>

    from .downloader import Downloader

  File
"/Users/local/anaconda3/lib/python3.7/site-packages/tcd/downloader.py",
line 12, in <module>

    from .formatter import Formatter

  File
"/Users/local/anaconda3/lib/python3.7/site-packages/tcd/formatter.py", line
5, in <module>

    from .formats.custom import Custom

  File
"/Users/local/anaconda3/lib/python3.7/site-packages/tcd/formats/custom.py",
line 5, in <module>

    from tcd.formats.format import Format

  File
"/Users/michaellin/anaconda3/lib/python3.7/site-packages/tcd/formats/format.py",
line 6, in <module>

    class Format:

  File
"/Users/local/anaconda3/lib/python3.7/site-packages/tcd/formats/format.py",
line 8, in Format

    def __init__(self, video: twitch.helix.Video, format_name: str):

AttributeError: module 'twitch.helix' has no attribute 'Video'

**Comment by PetterKraabol** [comment]
I'd use a normal Python installation instead of Conda in the meantime, which should work just fine.

**Comment by mik3up** [comment]
Thanks for being so responsive!

I am not familiar with the differences between a virtual environment and
regular python install. Are you recommending that I uninstall anaconda and
install python 3 from the python.org site? And help explain this?

I am running the command 'tcd' in terminal when I get the error messages.

-
Michael

**Comment by PetterKraabol** [comment]
On Mac, you use [Homebrew](https://brew.sh/) to install python with `brew install python`.
If you need the scipy packages that comes with Conda, you can just install them manually [using pip](https://www.scipy.org/install.html#installing-via-pip)

```bash
python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
```
